"""
PowerPoint Export Agent: generates a professional PPTX presentation from Aria outputs.

Slides produced:
  1  Title              — question + date
  2  Data Quality Score — Aria Score, grade, verdict, dimension table
  3  Key Insights       — 5 analyst findings as bullets
  4-7 Charts            — one chart image per slide (up to 4)
  8  Anomalies          — top 5 anomalies as a table
  9  Decisions          — 5 prioritised decisions as a table
  10 Forecasts          — forecast metric table
  11 Closing            — "Generated by Aria" credits

Theme: dark blue (#1a56db) header bar on every slide, white content area, Calibri font.
No Claude calls — pure python-pptx.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt, Emu

OUTPUT_DIR = "output/reports"

# ── Palette ────────────────────────────────────────────────────────────
C_BLUE    = RGBColor(0x1a, 0x56, 0xDB)   # header / accent
C_LBLUE   = RGBColor(0xDB, 0xEA, 0xFE)   # light blue fill for table headers
C_WHITE   = RGBColor(0xFF, 0xFF, 0xFF)
C_DARK    = RGBColor(0x11, 0x18, 0x27)   # body text
C_GREY    = RGBColor(0x6B, 0x72, 0x80)   # secondary text
C_RED     = RGBColor(0xDC, 0x26, 0x26)   # Critical
C_ORANGE  = RGBColor(0xEA, 0x58, 0x0C)   # High
C_GREEN   = RGBColor(0x05, 0x96, 0x69)   # Good/A grade
C_AMBER   = RGBColor(0xD9, 0x77, 0x06)   # Medium/C grade
C_ROW_ALT = RGBColor(0xF8, 0xFA, 0xFF)   # alternating row

# ── Dimensions (16:9 widescreen) ───────────────────────────────────────
SW = Inches(13.333)
SH = Inches(7.5)

HDR_H   = Inches(1.15)
BODY_T  = Inches(1.30)
BODY_H  = SH - BODY_T - Inches(0.2)
MARGIN  = Inches(0.55)
BODY_W  = SW - 2 * MARGIN

PRIORITY_COLOR = {"Critical": C_RED, "High": C_ORANGE, "Medium": C_BLUE}
GRADE_COLOR    = {"A": C_GREEN, "B": C_BLUE, "C": C_AMBER, "D": C_ORANGE, "F": C_RED}


class PPTXAgent:
    def __init__(self, output_dir: str = OUTPUT_DIR):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def run(
        self,
        question: str,
        analyst_output: dict,
        viz_output: dict,
        decision_output: dict,
        forecast_output: dict,
        quality_output: dict,
        anomaly_output: dict | None = None,
    ) -> dict:
        """
        Build and save a PPTX presentation from Aria pipeline outputs.

        Returns:
            dict with keys: pptx_path, slide_count
        """
        prs = Presentation()
        prs.slide_width  = SW
        prs.slide_height = SH
        blank = prs.slide_layouts[6]   # blank layout

        self._slide_title(prs, blank, question)
        self._slide_quality(prs, blank, quality_output or {})
        self._slide_insights(prs, blank, analyst_output or {})
        self._slides_charts(prs, blank, viz_output or {}, analyst_output or {})
        self._slide_anomalies(prs, blank, anomaly_output or {})
        self._slide_decisions(prs, blank, decision_output or {})
        self._slide_forecasts(prs, blank, forecast_output or {})
        self._slide_closing(prs, blank)

        ts   = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        path = os.path.join(self.output_dir, f"{ts}_aria_report.pptx")
        prs.save(path)
        return {"pptx_path": path, "slide_count": len(prs.slides)}

    # ------------------------------------------------------------------
    # Slide builders
    # ------------------------------------------------------------------

    def _slide_title(self, prs: Presentation, layout, question: str) -> None:
        slide = prs.slides.add_slide(layout)
        # Full-slide dark blue background
        bg = slide.shapes.add_shape(1, 0, 0, SW, SH)
        bg.fill.solid(); bg.fill.fore_color.rgb = C_BLUE
        bg.line.fill.background()

        self._txt(slide, "📊 Aria Analysis Report",
                  MARGIN, Inches(1.8), BODY_W, Inches(1.0),
                  size=40, bold=True, color=C_WHITE, align=PP_ALIGN.LEFT)
        self._txt(slide, question,
                  MARGIN, Inches(3.0), BODY_W, Inches(1.8),
                  size=22, color=RGBColor(0xBF, 0xDB, 0xFE), align=PP_ALIGN.LEFT)
        date_str = datetime.now(timezone.utc).strftime("%B %d, %Y")
        self._txt(slide, f"Generated by Aria · {date_str}",
                  MARGIN, Inches(5.8), BODY_W, Inches(0.5),
                  size=12, color=RGBColor(0x93, 0xC5, 0xFD), align=PP_ALIGN.LEFT)

    def _slide_quality(self, prs: Presentation, layout, q: dict) -> None:
        slide = prs.slides.add_slide(layout)
        self._header(slide, "Data Quality Score")

        score   = q.get("overall_score", 0)
        grade   = q.get("grade", "?")
        verdict = q.get("verdict", "")
        dims    = q.get("dimension_scores", {})
        g_color = GRADE_COLOR.get(grade, C_GREY)

        # Big score
        self._txt(slide, f"{score:.0f}/100",
                  MARGIN, BODY_T, Inches(3.5), Inches(1.5),
                  size=64, bold=True, color=C_BLUE)
        self._txt(slide, f"Grade  {grade}",
                  MARGIN, BODY_T + Inches(1.5), Inches(3.5), Inches(0.7),
                  size=28, bold=True, color=g_color)
        # Verdict
        self._txt(slide, verdict,
                  MARGIN, BODY_T + Inches(2.3), Inches(6.5), Inches(2.8),
                  size=11, color=C_DARK, wrap=True)

        # Dimension table
        dim_weights = {"completeness": 20, "uniqueness": 20, "consistency": 20,
                       "validity": 20, "timeliness": 10, "uniformity": 10}
        rows = [("Dimension", "Score", "Max")] + [
            (d.title(), f"{dims.get(d, 0):.1f}", str(w))
            for d, w in dim_weights.items()
        ]
        self._table(slide,
                    rows,
                    left=SW - MARGIN - Inches(5.5), top=BODY_T,
                    width=Inches(5.5), height=Inches(4.0),
                    header_color=C_BLUE, col_widths=[Inches(2.8), Inches(1.35), Inches(1.35)])

    def _slide_insights(self, prs: Presentation, layout, ao: dict) -> None:
        slide = prs.slides.add_slide(layout)
        self._header(slide, "Key Insights")
        insights = ao.get("insights", [])
        top = BODY_T
        for i, insight in enumerate(insights[:5], 1):
            bullet = f"  {i}.  {insight}"
            self._txt(slide, bullet,
                      MARGIN, top, BODY_W, Inches(0.85),
                      size=11, color=C_DARK, wrap=True)
            top += Inches(0.9)

    def _slides_charts(self, prs: Presentation, layout, vo: dict, ao: dict) -> None:
        paths  = vo.get("figure_paths", [])
        metas  = ao.get("suggested_charts", [])
        for i, img_path in enumerate(paths[:4]):
            if not os.path.exists(img_path):
                continue
            slide = prs.slides.add_slide(layout)
            title = metas[i].get("title", f"Chart {i+1}") if i < len(metas) else f"Chart {i+1}"
            # Truncate long titles
            if len(title) > 80:
                title = title[:77] + "…"
            self._header(slide, title)
            try:
                slide.shapes.add_picture(img_path,
                                         MARGIN, BODY_T,
                                         BODY_W, BODY_H)
            except Exception:
                self._txt(slide, f"[Image: {Path(img_path).name}]",
                          MARGIN, BODY_T, BODY_W, Inches(0.5), size=11, color=C_GREY)

    def _slide_anomalies(self, prs: Presentation, layout, ao: dict) -> None:
        anomalies = ao.get("anomalies", [])
        slide = prs.slides.add_slide(layout)
        self._header(slide, "Anomaly Detection")
        if not anomalies:
            self._txt(slide, "No significant anomalies detected.",
                      MARGIN, BODY_T, BODY_W, Inches(0.5), size=14, color=C_GREY)
            return
        sc = ao.get("severity_counts", {})
        self._txt(slide,
                  f"🔴 {sc.get('high',0)} Critical  ·  🟠 {sc.get('medium',0)} Medium  ·  Total: {len(anomalies)}",
                  MARGIN, BODY_T, BODY_W, Inches(0.45), size=12, color=C_DARK)
        top5 = anomalies[:5]
        rows = [("Entity", "Column", "Value", "Severity", "Reason")] + [
            (
                str(a.get("entity", ""))[:25],
                str(a.get("column", ""))[:20],
                str(a.get("value", "")),
                a.get("severity", "").title(),
                str(a.get("reason", ""))[:60],
            )
            for a in top5
        ]
        self._table(slide, rows,
                    left=MARGIN, top=BODY_T + Inches(0.5),
                    width=BODY_W, height=Inches(4.5),
                    header_color=C_BLUE,
                    col_widths=[Inches(2.0), Inches(2.2), Inches(1.3), Inches(1.3), Inches(5.5)])

    def _slide_decisions(self, prs: Presentation, layout, do: dict) -> None:
        decisions = do.get("decisions", [])
        slide = prs.slides.add_slide(layout)
        self._header(slide, "Strategic Decisions")
        if not decisions:
            self._txt(slide, "No decisions generated.",
                      MARGIN, BODY_T, BODY_W, Inches(0.5), size=14, color=C_GREY)
            return
        rows = [("Priority", "Timeline", "Action")] + [
            (
                d.get("priority", ""),
                d.get("timeline", ""),
                str(d.get("action", ""))[:100],
            )
            for d in decisions[:5]
        ]
        tbl = self._table(slide, rows,
                          left=MARGIN, top=BODY_T,
                          width=BODY_W, height=Inches(5.6),
                          header_color=C_BLUE,
                          col_widths=[Inches(1.6), Inches(1.6), Inches(10.1)])
        if tbl:
            for i, d in enumerate(decisions[:5], 1):
                priority = d.get("priority", "")
                c = PRIORITY_COLOR.get(priority, C_DARK)
                cell = tbl.cell(i, 0)
                cell.fill.solid()
                cell.fill.fore_color.rgb = c
                for para in cell.text_frame.paragraphs:
                    for run in para.runs:
                        run.font.color.rgb = C_WHITE
                        run.font.bold = True

    def _slide_forecasts(self, prs: Presentation, layout, fo: dict) -> None:
        forecasts = fo.get("forecasts", [])
        slide = prs.slides.add_slide(layout)
        self._header(slide, "Forecasts")
        if not forecasts:
            self._txt(slide, "No statistically significant trends found.",
                      MARGIN, BODY_T, BODY_W, Inches(0.5), size=14, color=C_GREY)
            return
        # Determine forecast years from first forecast entry
        first  = forecasts[0]
        fy_keys = sorted([k for k in first if k.startswith("forecast_")])
        fy_yrs  = [k.replace("forecast_", "") for k in fy_keys]
        header_row = ["Metric", "R²", "Last Value"] + fy_yrs
        rows = [tuple(header_row)] + [
            (
                f.get("metric", "").replace("_", " ").title(),
                f"{f.get('r_squared', 0):.2f}",
                f"{f.get('last_value', '')}",
                *[str(round(f.get(k, 0), 4)) for k in fy_keys],
            )
            for f in forecasts[:7]
        ]
        col_widths = [Inches(4.0), Inches(1.2), Inches(1.8)] + [Inches(2.1)] * len(fy_yrs)
        self._table(slide, rows,
                    left=MARGIN, top=BODY_T,
                    width=BODY_W, height=min(Inches(5.8), Inches(0.7 * len(rows))),
                    header_color=C_BLUE, col_widths=col_widths[:len(header_row)])

    def _slide_closing(self, prs: Presentation, layout) -> None:
        slide = prs.slides.add_slide(layout)
        bg = slide.shapes.add_shape(1, 0, 0, SW, SH)
        bg.fill.solid(); bg.fill.fore_color.rgb = C_BLUE
        bg.line.fill.background()
        self._txt(slide, "Thank You",
                  0, Inches(2.2), SW, Inches(1.2),
                  size=54, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
        self._txt(slide, "Generated by Aria — Autonomous Reasoning & Insight Agent",
                  0, Inches(3.6), SW, Inches(0.6),
                  size=16, color=RGBColor(0xBF, 0xDB, 0xFE), align=PP_ALIGN.CENTER)
        self._txt(slide, "Powered by Claude · Anthropic",
                  0, Inches(4.3), SW, Inches(0.45),
                  size=12, color=RGBColor(0x93, 0xC5, 0xFD), align=PP_ALIGN.CENTER)

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------

    def _header(self, slide, title: str) -> None:
        """Dark blue full-width header bar with white title."""
        bar = slide.shapes.add_shape(1, 0, 0, SW, HDR_H)
        bar.fill.solid(); bar.fill.fore_color.rgb = C_BLUE
        bar.line.fill.background()
        tf = bar.text_frame
        tf.word_wrap = False
        p  = tf.paragraphs[0]
        p.alignment = PP_ALIGN.LEFT
        run = p.add_run()
        run.text = f"  {title}"
        run.font.size  = Pt(26)
        run.font.bold  = True
        run.font.color.rgb = C_WHITE
        # vertically centre by padding
        tf.margin_top = Inches(0.22)

    def _txt(self, slide, text: str, left, top, width, height,
             size: int = 12, bold: bool = False,
             color: RGBColor = C_DARK,
             align: PP_ALIGN = PP_ALIGN.LEFT,
             wrap: bool = False) -> None:
        box = slide.shapes.add_textbox(left, top, width, height)
        tf  = box.text_frame
        tf.word_wrap = wrap
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = text
        run.font.size  = Pt(size)
        run.font.bold  = bold
        run.font.color.rgb = color

    def _table(self, slide, rows: list[tuple],
               left, top, width, height,
               header_color: RGBColor = C_BLUE,
               col_widths: list | None = None):
        """Add a formatted table. Returns the table object."""
        if not rows:
            return None
        n_rows = len(rows)
        n_cols = len(rows[0])
        tbl_obj = slide.shapes.add_table(n_rows, n_cols, left, top, width, height)
        tbl     = tbl_obj.table

        if col_widths:
            for i, w in enumerate(col_widths[:n_cols]):
                tbl.columns[i].width = w

        for r_idx, row in enumerate(rows):
            for c_idx, cell_text in enumerate(row):
                cell = tbl.cell(r_idx, c_idx)
                cell.text = str(cell_text)
                para = cell.text_frame.paragraphs[0]
                run  = para.runs[0] if para.runs else para.add_run()
                is_header = (r_idx == 0)
                run.font.size  = Pt(9 if not is_header else 10)
                run.font.bold  = is_header
                run.font.color.rgb = C_WHITE if is_header else C_DARK
                if is_header:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = header_color
                elif r_idx % 2 == 0:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = C_ROW_ALT

        return tbl
