[theme]
base                     = "light"
backgroundColor          = "#f0f2ff"
secondaryBackgroundColor = "#ffffff"
textColor                = "#0f172a"
primaryColor             = "#667eea"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
